[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Command|Option"

[font]
size = 22.0

[font.bold]
family = "ComicCodeLigatures Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicCodeLigatures Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicCodeLigatures Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[keyboard]
